### ISSUE TITLE
Nestajanje ćelija

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-087-k-osmos#3]
Kad veća ćelija predje preko manje, manja bi trebalo da nestane.

Preciznije, kad se ćelije dodirnu, veća se povećava postepeno, a manja smanjuje dok ne nestane.

**Comment by NemanjaIlic** [comment]
Celije se tako i ponasaju na inicijalnoj sceni (prozoru), ali ima bag sa promenom rezolucije

**Comment by ivan-cukic-matf** [comment]
Celije odjednom promene velicinu, ne postepeno.

**Comment by NemanjaIlic** [comment]
Aha, ako doradim ovo do ispit da li imam pravo da izadjem na usmeni sada u februaru ili cekam sl. rok?
